name: goreleaser

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      - name: prepare the binaries
        run: go run -ldflags "-w -s -X main.version=`git describe --exact-match --tags $(git log -n1 --pretty='%h')`" tools/prepare.go
      - name: release dry run
        if: "!startswith(github.ref, 'refs/tags/v')"
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: --rm-dist --skip-validate --skip-publish --snapshot
      - name: release
        if: startswith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}